from selenium.webdriver.common.by import By
def demo_myql_oracle(driver):
    state = driver.execute_script('return $state;');
    
    assert not True or driver.find_elements(By.ID, 'theAge_div_17')[0].is_displayed(), 'true evaluated to true, however theAge_div_17 was not displayed'
    assert not True or driver.find_elements(By.ID, 'theAge2_div_92')[0].is_displayed(), 'true evaluated to true, however theAge2_div_92 was not displayed'
    assert not True or driver.find_elements(By.ID, 'ofAge_div_178')[0].is_displayed(), 'true evaluated to true, however ofAge_div_178 was not displayed'
    assert not True or driver.find_elements(By.ID, 'ofAge2_div_282')[0].is_displayed(), 'true evaluated to true, however ofAge2_div_282 was not displayed'
    assert not (True and ((((state['theAge'] >= 18) and (state['ofAge'] == True)) and (state['ofAge'] == state['ofAge2'])) and (state['theAge'] == state['theAge2']))) or driver.find_elements(By.ID, 'hourlyRate_div_533')[0].is_displayed(), 'true && theAge >= 18 &&        ofAge == true &&        ofAge == ofAge2 &&        theAge == theAge2 evaluated to true, however hourlyRate_div_533 was not displayed'
    assert not ((True and ((((state['theAge'] >= 18) and (state['ofAge'] == True)) and (state['ofAge'] == state['ofAge2'])) and (state['theAge'] == state['theAge2']))) and (state['hourlyRate'] <= 5)) or driver.find_elements(By.ID, 'lowRemark_div_688')[0].is_displayed(), 'true && theAge >= 18 &&        ofAge == true &&        ofAge == ofAge2 &&        theAge == theAge2 && hourlyRate <= 5 evaluated to true, however lowRemark_div_688 was not displayed'
    assert not (((True and ((((state['theAge'] >= 18) and (state['ofAge'] == True)) and (state['ofAge'] == state['ofAge2'])) and (state['theAge'] == state['theAge2']))) and not (((state['hourlyRate'] <= 5)))) and (state['hourlyRate'] <= 15)) or driver.find_elements(By.ID, 'averageRemark_div_801')[0].is_displayed(), 'true && theAge >= 18 &&        ofAge == true &&        ofAge == ofAge2 &&        theAge == theAge2 && !(hourlyRate <= 5) && hourlyRate <= 15 evaluated to true, however averageRemark_div_801 was not displayed'
    assert not (((True and ((((state['theAge'] >= 18) and (state['ofAge'] == True)) and (state['ofAge'] == state['ofAge2'])) and (state['theAge'] == state['theAge2']))) and not (((state['hourlyRate'] <= 5)))) and not (((state['hourlyRate'] <= 15)))) or driver.find_elements(By.ID, 'highRemark_div_893')[0].is_displayed(), 'true && theAge >= 18 &&        ofAge == true &&        ofAge == ofAge2 &&        theAge == theAge2 && !(hourlyRate <= 5) && !(hourlyRate <= 15) evaluated to true, however highRemark_div_893 was not displayed'
    assert not (True and ((((state['theAge'] >= 18) and (state['ofAge'] == True)) and (state['ofAge'] == state['ofAge2'])) and (state['theAge'] == state['theAge2']))) or driver.find_elements(By.ID, 'hoursAWeek_div_979')[0].is_displayed(), 'true && theAge >= 18 &&        ofAge == true &&        ofAge == ofAge2 &&        theAge == theAge2 evaluated to true, however hoursAWeek_div_979 was not displayed'
    assert not (True and ((((state['theAge'] >= 18) and (state['ofAge'] == True)) and (state['ofAge'] == state['ofAge2'])) and (state['theAge'] == state['theAge2']))) or driver.find_elements(By.ID, 'weeklyIncome_div_1050')[0].is_displayed(), 'true && theAge >= 18 &&        ofAge == true &&        ofAge == ofAge2 &&        theAge == theAge2 evaluated to true, however weeklyIncome_div_1050 was not displayed'
    assert state['weeklyIncome'] == (state['hourlyRate'] * state['hoursAWeek']), ' weeklyIncome was not the same as hourlyRate * hoursAWeek'
    assert not (True and not ((((((state['theAge'] >= 18) and (state['ofAge'] == True)) and (state['ofAge'] == state['ofAge2'])) and (state['theAge'] == state['theAge2']))))) or driver.find_elements(By.ID, 'theAgeToYoung_div_1200')[0].is_displayed(), 'true && !(theAge >= 18 &&        ofAge == true &&        ofAge == ofAge2 &&        theAge == theAge2) evaluated to true, however theAgeToYoung_div_1200 was not displayed'
